$env:DATABASE_URL = "sqlite+aiosqlite:///./marketpilot.db"
$env:REDIS_URL = "redis://localhost:6379/0"
$env:JWT_SECRET = "dev-secret-key-change-in-production-please"
$env:JWT_REFRESH_SECRET = "dev-refresh-secret-key-change-in-production"
$env:JWT_ALGORITHM = "HS256"
$env:JWT_ACCESS_TOKEN_EXPIRE_MINUTES = "15"
$env:JWT_REFRESH_TOKEN_EXPIRE_DAYS = "7"
$env:GEMINI_API_KEY = ""
$env:OPENAI_API_KEY = ""
$env:CORS_ORIGINS = "http://localhost:3000,http://localhost:5173"
$env:ENVIRONMENT = "development"
$env:APP_NAME = "MarketPilot AI"
$env:APP_VERSION = "1.0.0"
python -m uvicorn app.main:app --host 127.0.0.1 --port 8000
